export const buyTogetherData: any = {
  id: 82,
  name: 'Dia das Sandalia',
  title: 'Aproveite já',
  buyButtonText: 'Compre agora',
  productId: 2915736,
  colorId: null,
  dateFrom: '2023-10-05',
  dateTo: null,
  active: true,
  product: {
    id: '9480233',
    name: 'Sandália Diesel Sa-Valla',
    slug: 'sandalia-diesel-sa-valla',
    color: {
      id: 266403,
      name: 'Preto',
      slug: 'preto',
      hexadecimal: '#000000',
      position: 1,
      __typename: 'ShowcaseColor',
    },
    colors: [
      {
        id: 266403,
        name: 'Preto',
        slug: 'preto',
        hexadecimal: '#000000',
        image: null,
        position: 1,
        __typename: 'ShowcaseColor',
      },
    ],
    images: [
      {
        id: null,
        productId: null,
        src: 'https://optimizer.dchomolog.dooca.store/103779/products/203244.jpg?v=1696526309',
        alt: null,
        colorIds: [266403],
        variationIds: [],
        position: 1,
        __typename: 'ShowcaseImage',
      },
      {
        id: null,
        productId: null,
        src: 'https://optimizer.dchomolog.dooca.store/103779/products/203246.jpg?v=1696526309',
        alt: null,
        colorIds: [266403],
        variationIds: [],
        position: 2,
        __typename: 'ShowcaseImage',
      },
      {
        id: null,
        productId: null,
        src: 'https://optimizer.dchomolog.dooca.store/103779/products/203245.jpg?v=1696526309',
        alt: null,
        colorIds: [266403],
        variationIds: [],
        position: 3,
        __typename: 'ShowcaseImage',
      },
    ],
    payments: [],
    gtin: null,
    mpn: null,
    additionalShippingTime: null,
    externalId: null,
    categoryDefaultId: null,
    hotsiteId: null,
    description:
      '<p>SANDALIA, MARCA DIESEL, COMERCIALMENTE DENOMINADA SLIDE, DE USO MASCULINO, ADULTO.</p>',
    shortDescription: null,
    relevance: 1,
    tags: null,
    minQuantity: 1,
    maxQuantity: null,
    isSellInKitOnly: null,
    metaTitle: null,
    metaDescription: null,
    metaKeywords: null,
    isKit: null,
    kitMarkup: 1,
    isVirtual: null,
    isPreSale: null,
    video: null,
    weight: null,
    depth: null,
    width: null,
    height: null,
    priceOutOfStock: null,
    isSellOutOfStock: null,
    additionalTimeOutOfStock: null,
    balance: null,
    price: '250.00',
    minPriceRange: null,
    maxPriceRange: null,
    hasPriceRange: null,
    priceCompare: 300,
    discount: 16.67,
    billetDiscount: null,
    paymentsReason: null,
    warranty: null,
    model: null,
    gender: null,
    ageGroup: null,
    brand: null,
    category: null,
    categories: null,
    reference: null,
    attribute: {
      id: 462525,
      name: '40',
      slug: '40',
      attributeId: 74679,
      attributeName: 'Tamanho calçados',
      position: 6,
      isActive: true,
      __typename: 'ShowcaseAttributeValue',
    },
    attributeSecondary: {
      id: 462516,
      name: 'Sintético',
      slug: 'sintetico',
      attributeId: 74678,
      attributeName: 'Material',
      position: 2,
      isActive: true,
      __typename: 'ShowcaseAttributeValue',
    },
    features: null,
    productId: 2915736,
    createdAt: '1696526307',
    variations: [
      {
        id: '9480233',
        name: 'Sandália Diesel Sa-Valla',
        slug: 'sandalia-diesel-sa-valla',
        gtin: null,
        mpn: null,
        additionalShippingTime: null,
        externalId: null,
        categoryDefaultId: null,
        hotsiteId: null,
        description:
          '<p>SANDALIA, MARCA DIESEL, COMERCIALMENTE DENOMINADA SLIDE, DE USO MASCULINO, ADULTO.</p>',
        shortDescription: null,
        relevance: 1,
        reference: null,
        tags: null,
        minQuantity: 1,
        maxQuantity: null,
        isSellInKitOnly: null,
        metaTitle: null,
        metaDescription: null,
        metaKeywords: null,
        isKit: null,
        kitMarkup: 1,
        isVirtual: null,
        isPreSale: null,
        video: null,
        weight: null,
        depth: null,
        width: null,
        height: null,
        priceOutOfStock: null,
        isSellOutOfStock: null,
        additionalTimeOutOfStock: null,
        balance: null,
        price: '250.00',
        minPriceRange: null,
        maxPriceRange: null,
        hasPriceRange: null,
        priceCompare: 300,
        discount: 16.67,
        billetDiscount: null,
        paymentsReason: null,
        warranty: null,
        model: null,
        gender: null,
        ageGroup: null,
        productId: 2915736,
        createdAt: '1696526307',
        sku: null,
        colors: [
          {
            id: 266403,
            name: 'Preto',
            slug: 'preto',
            hexadecimal: '#000000',
            position: 1,
            __typename: 'ShowcaseColor',
          },
        ],
        isGift: null,
        __typename: 'Showcase',
      },
      {
        id: '9480234',
        name: 'Sandália Diesel Sa-Valla',
        slug: 'sandalia-diesel-sa-valla',
        gtin: null,
        mpn: null,
        additionalShippingTime: null,
        externalId: null,
        categoryDefaultId: null,
        hotsiteId: null,
        description:
          '<p>SANDALIA, MARCA DIESEL, COMERCIALMENTE DENOMINADA SLIDE, DE USO MASCULINO, ADULTO.</p>',
        shortDescription: null,
        relevance: 1,
        reference: null,
        tags: null,
        minQuantity: 1,
        maxQuantity: null,
        isSellInKitOnly: null,
        metaTitle: null,
        metaDescription: null,
        metaKeywords: null,
        isKit: null,
        kitMarkup: 1,
        isVirtual: null,
        isPreSale: null,
        video: null,
        weight: null,
        depth: null,
        width: null,
        height: null,
        priceOutOfStock: null,
        isSellOutOfStock: null,
        additionalTimeOutOfStock: null,
        balance: null,
        price: '250.00',
        minPriceRange: null,
        maxPriceRange: null,
        hasPriceRange: null,
        priceCompare: 300,
        discount: 16.67,
        billetDiscount: null,
        paymentsReason: null,
        warranty: null,
        model: null,
        gender: null,
        ageGroup: null,
        productId: 2915736,
        createdAt: '1696526307',
        sku: null,
        colors: [
          {
            id: 266403,
            name: 'Preto',
            slug: 'preto',
            hexadecimal: '#000000',
            position: 1,
            __typename: 'ShowcaseColor',
          },
        ],
        isGift: null,
        __typename: 'Showcase',
      },
      {
        id: '9480235',
        name: 'Sandália Diesel Sa-Valla',
        slug: 'sandalia-diesel-sa-valla',
        gtin: null,
        mpn: null,
        additionalShippingTime: null,
        externalId: null,
        categoryDefaultId: null,
        hotsiteId: null,
        description:
          '<p>SANDALIA, MARCA DIESEL, COMERCIALMENTE DENOMINADA SLIDE, DE USO MASCULINO, ADULTO.</p>',
        shortDescription: null,
        relevance: 1,
        reference: null,
        tags: null,
        minQuantity: 1,
        maxQuantity: null,
        isSellInKitOnly: null,
        metaTitle: null,
        metaDescription: null,
        metaKeywords: null,
        isKit: null,
        kitMarkup: 1,
        isVirtual: null,
        isPreSale: null,
        video: null,
        weight: null,
        depth: null,
        width: null,
        height: null,
        priceOutOfStock: null,
        isSellOutOfStock: null,
        additionalTimeOutOfStock: null,
        balance: null,
        price: '250.00',
        minPriceRange: null,
        maxPriceRange: null,
        hasPriceRange: null,
        priceCompare: 300,
        discount: 16.67,
        billetDiscount: null,
        paymentsReason: null,
        warranty: null,
        model: null,
        gender: null,
        ageGroup: null,
        productId: 2915736,
        createdAt: '1696526307',
        sku: null,
        colors: [
          {
            id: 266403,
            name: 'Preto',
            slug: 'preto',
            hexadecimal: '#000000',
            position: 1,
            __typename: 'ShowcaseColor',
          },
        ],
        isGift: null,
        __typename: 'Showcase',
      },
    ],
    components: null,
    componentGroups: null,
    sku: null,
    isGift: null,
    releaseDate: null,
    __typename: 'Product',
  },
  productsPivot: [
    {
      id: '9480064',
      name: 'Camiseta Nike SB',
      slug: 'camiseta-nike-sb',
      color: {
        id: 266402,
        name: 'Azul',
        slug: 'azul',
        hexadecimal: '#1500B0',
        position: 1,
        __typename: 'ShowcaseColor',
      },
      colors: [
        {
          id: 266402,
          name: 'Azul',
          slug: 'azul',
          hexadecimal: '#1500B0',
          image: null,
          position: 1,
          __typename: 'ShowcaseColor',
        },
        {
          id: 266403,
          name: 'Preto',
          slug: 'preto',
          hexadecimal: '#000000',
          image: null,
          position: 2,
          __typename: 'ShowcaseColor',
        },
      ],
      images: [
        {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/products/02302015.jpeg?v=1695153441',
          alt: null,
          colorIds: [266402],
          variationIds: [],
          position: 4,
          __typename: 'ShowcaseImage',
        },
        {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/products/02302015a1.jpeg?v=1695153441',
          alt: null,
          colorIds: [266402],
          variationIds: [],
          position: 5,
          __typename: 'ShowcaseImage',
        },
        {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/products/02302015a4.jpeg?v=1695153441',
          alt: null,
          colorIds: [266402],
          variationIds: [],
          position: 6,
          __typename: 'ShowcaseImage',
        },
        {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/products/02302015a2.jpeg?v=1695153441',
          alt: null,
          colorIds: [266402],
          variationIds: [],
          position: 7,
          __typename: 'ShowcaseImage',
        },
      ],
      payments: [],
      gtin: null,
      mpn: null,
      additionalShippingTime: null,
      externalId: null,
      categoryDefaultId: null,
      hotsiteId: null,
      description:
        '<p>Fabricada com tecido jersey macio, a camiseta Nike SB é uma peça essencial do skate com caimento solto e o logotipo clássico no peito.</p>',
      shortDescription: null,
      relevance: 1,
      tags: null,
      minQuantity: 1,
      maxQuantity: null,
      isSellInKitOnly: null,
      metaTitle: null,
      metaDescription: null,
      metaKeywords: null,
      isKit: null,
      kitMarkup: 1,
      isVirtual: null,
      isPreSale: null,
      video: null,
      weight: 0.2,
      depth: 49,
      width: 53,
      height: 74,
      priceOutOfStock: null,
      isSellOutOfStock: null,
      additionalTimeOutOfStock: null,
      balance: 12,
      price: '149.00',
      minPriceRange: null,
      maxPriceRange: null,
      hasPriceRange: null,
      priceCompare: 169,
      discount: 11.83,
      billetDiscount: null,
      paymentsReason: null,
      warranty: null,
      model: null,
      gender: null,
      ageGroup: null,
      brand: {
        id: 136884,
        name: 'Nike',
        slug: 'nike',
        description: null,
        shortDescription: null,
        image: {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/brands/open-graph-main-image.jpg?v=1695847397',
          alt: null,
          colorIds: null,
          variationIds: null,
          position: null,
          __typename: 'ShowcaseImage',
        },
        banner: null,
        __typename: 'ShowcaseBrand',
      },
      category: null,
      categories: [
        {
          id: 318555,
          name: 'Camisetas',
          slug: 'camisetas',
          description: null,
          breadcrumb: 'Camisetas',
          googleTaxonomyId: null,
          __typename: 'ShowcaseCategory',
        },
      ],
      reference: null,
      attribute: null,
      attributeSecondary: null,
      features: null,
      productId: 2915660,
      createdAt: '1695153440',
      variations: [
        {
          id: '9480064',
          name: 'Camiseta Nike SB',
          slug: 'camiseta-nike-sb',
          gtin: null,
          mpn: null,
          additionalShippingTime: null,
          externalId: null,
          categoryDefaultId: null,
          hotsiteId: null,
          description:
            '<p>Fabricada com tecido jersey macio, a camiseta Nike SB é uma peça essencial do skate com caimento solto e o logotipo clássico no peito.</p>',
          shortDescription: null,
          relevance: 1,
          reference: null,
          tags: null,
          minQuantity: 1,
          maxQuantity: null,
          isSellInKitOnly: null,
          metaTitle: null,
          metaDescription: null,
          metaKeywords: null,
          isKit: null,
          kitMarkup: 1,
          isVirtual: null,
          isPreSale: null,
          video: null,
          weight: 0.2,
          depth: 49,
          width: 53,
          height: 74,
          priceOutOfStock: null,
          isSellOutOfStock: null,
          additionalTimeOutOfStock: null,
          balance: 12,
          price: '149.00',
          minPriceRange: null,
          maxPriceRange: null,
          hasPriceRange: null,
          priceCompare: 169,
          discount: 11.83,
          billetDiscount: null,
          paymentsReason: null,
          warranty: null,
          model: null,
          gender: null,
          ageGroup: null,
          productId: 2915660,
          createdAt: '1695153440',
          sku: null,
          colors: [
            {
              id: 266402,
              name: 'Azul',
              slug: 'azul',
              hexadecimal: '#1500B0',
              position: 1,
              __typename: 'ShowcaseColor',
            },
            {
              id: 266403,
              name: 'Preto',
              slug: 'preto',
              hexadecimal: '#000000',
              position: 2,
              __typename: 'ShowcaseColor',
            },
          ],
          isGift: null,
          __typename: 'Showcase',
        },
        {
          id: '9480065',
          name: 'Camiseta Nike SB',
          slug: 'camiseta-nike-sb',
          gtin: null,
          mpn: null,
          additionalShippingTime: null,
          externalId: null,
          categoryDefaultId: null,
          hotsiteId: null,
          description:
            '<p>Fabricada com tecido jersey macio, a camiseta Nike SB é uma peça essencial do skate com caimento solto e o logotipo clássico no peito.</p>',
          shortDescription: null,
          relevance: 1,
          reference: null,
          tags: null,
          minQuantity: 1,
          maxQuantity: null,
          isSellInKitOnly: null,
          metaTitle: null,
          metaDescription: null,
          metaKeywords: null,
          isKit: null,
          kitMarkup: 1,
          isVirtual: null,
          isPreSale: null,
          video: null,
          weight: 0.2,
          depth: 49,
          width: 53,
          height: 74,
          priceOutOfStock: null,
          isSellOutOfStock: null,
          additionalTimeOutOfStock: null,
          balance: 12,
          price: '149.00',
          minPriceRange: null,
          maxPriceRange: null,
          hasPriceRange: null,
          priceCompare: 169,
          discount: 11.83,
          billetDiscount: null,
          paymentsReason: null,
          warranty: null,
          model: null,
          gender: null,
          ageGroup: null,
          productId: 2915660,
          createdAt: '1695153440',
          sku: null,
          colors: [
            {
              id: 266402,
              name: 'Azul',
              slug: 'azul',
              hexadecimal: '#1500B0',
              position: 1,
              __typename: 'ShowcaseColor',
            },
            {
              id: 266403,
              name: 'Preto',
              slug: 'preto',
              hexadecimal: '#000000',
              position: 2,
              __typename: 'ShowcaseColor',
            },
          ],
          isGift: null,
          __typename: 'Showcase',
        },
      ],
      components: null,
      componentGroups: null,
      sku: null,
      isGift: null,
      releaseDate: null,
      __typename: 'Product',
    },
    {
      id: '9480162',
      name: 'Boné Jordan Flight MVP',
      slug: 'bone-jordan-flight-mvp',
      color: null,
      colors: null,
      images: [
        {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/products/026554id.jpeg?v=1695991461',
          alt: null,
          colorIds: [],
          variationIds: [],
          position: 1,
          __typename: 'ShowcaseImage',
        },
        {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/products/026554ida1.jpeg?v=1695991461',
          alt: null,
          colorIds: [],
          variationIds: [],
          position: 2,
          __typename: 'ShowcaseImage',
        },
      ],
      payments: [],
      gtin: null,
      mpn: null,
      additionalShippingTime: null,
      externalId: null,
      categoryDefaultId: null,
      hotsiteId: null,
      description:
        '<p>Arrase de Jordan da cabeça aos pés. O Boné Pro é um snapback estruturado feito com uma coroa trançada para um visual elevado, feito para durar. Além disso, ele é decorado com gráficos Jordan em destaque.</p>\n<p><br></p>\n<p><strong>Benefícios</strong></p>\n<ul><li>Coroa estruturada fica alta para um visual clássico.</li><li>Gráfico bordado adiciona textura à coroa macia.</li><li>Faixa antitranspiração proporciona uma sensação fresca e confortável.</li><li>Um fecho ajustável proporciona um caimento personalizado.</li></ul>\n<p><br></p>\n<p><strong>Detalhes do Produto</strong></p>\n<ul><li>Corpo: 100% poliéster. Parte de trás do painel da frente: 100% poliéster.</li><li>Não lavar</li><li>Importado</li></ul>',
      shortDescription: null,
      relevance: 1,
      tags: null,
      minQuantity: 1,
      maxQuantity: null,
      isSellInKitOnly: null,
      metaTitle: null,
      metaDescription: null,
      metaKeywords: null,
      isKit: null,
      kitMarkup: 1,
      isVirtual: null,
      isPreSale: null,
      video: null,
      weight: 0,
      depth: null,
      width: null,
      height: null,
      priceOutOfStock: null,
      isSellOutOfStock: null,
      additionalTimeOutOfStock: null,
      balance: 20,
      price: '249.00',
      minPriceRange: null,
      maxPriceRange: null,
      hasPriceRange: null,
      priceCompare: null,
      discount: null,
      billetDiscount: null,
      paymentsReason: null,
      warranty: null,
      model: null,
      gender: null,
      ageGroup: null,
      brand: {
        id: 136884,
        name: 'Nike',
        slug: 'nike',
        description: null,
        shortDescription: null,
        image: {
          id: null,
          productId: null,
          src: 'https://optimizer.dchomolog.dooca.store/103779/brands/open-graph-main-image.jpg?v=1695847397',
          alt: null,
          colorIds: null,
          variationIds: null,
          position: null,
          __typename: 'ShowcaseImage',
        },
        banner: null,
        __typename: 'ShowcaseBrand',
      },
      category: null,
      categories: null,
      reference: null,
      attribute: null,
      attributeSecondary: null,
      features: null,
      productId: 2915719,
      createdAt: '1695991461',
      variations: [
        {
          id: '9480162',
          name: 'Boné Jordan Flight MVP',
          slug: 'bone-jordan-flight-mvp',
          gtin: null,
          mpn: null,
          additionalShippingTime: null,
          externalId: null,
          categoryDefaultId: null,
          hotsiteId: null,
          description:
            '<p>Arrase de Jordan da cabeça aos pés. O Boné Pro é um snapback estruturado feito com uma coroa trançada para um visual elevado, feito para durar. Além disso, ele é decorado com gráficos Jordan em destaque.</p>\n<p><br></p>\n<p><strong>Benefícios</strong></p>\n<ul><li>Coroa estruturada fica alta para um visual clássico.</li><li>Gráfico bordado adiciona textura à coroa macia.</li><li>Faixa antitranspiração proporciona uma sensação fresca e confortável.</li><li>Um fecho ajustável proporciona um caimento personalizado.</li></ul>\n<p><br></p>\n<p><strong>Detalhes do Produto</strong></p>\n<ul><li>Corpo: 100% poliéster. Parte de trás do painel da frente: 100% poliéster.</li><li>Não lavar</li><li>Importado</li></ul>',
          shortDescription: null,
          relevance: 1,
          reference: null,
          tags: null,
          minQuantity: 1,
          maxQuantity: null,
          isSellInKitOnly: null,
          metaTitle: null,
          metaDescription: null,
          metaKeywords: null,
          isKit: null,
          kitMarkup: 1,
          isVirtual: null,
          isPreSale: null,
          video: null,
          weight: 0,
          depth: null,
          width: null,
          height: null,
          priceOutOfStock: null,
          isSellOutOfStock: null,
          additionalTimeOutOfStock: null,
          balance: 20,
          price: '249.00',
          minPriceRange: null,
          maxPriceRange: null,
          hasPriceRange: null,
          priceCompare: null,
          discount: null,
          billetDiscount: null,
          paymentsReason: null,
          warranty: null,
          model: null,
          gender: null,
          ageGroup: null,
          productId: 2915719,
          createdAt: '1695991461',
          sku: null,
          colors: null,
          isGift: null,
          __typename: 'Showcase',
        },
      ],
      components: null,
      componentGroups: null,
      sku: null,
      isGift: null,
      releaseDate: null,
      __typename: 'Product',
    },
  ],
  __typename: 'BuyTogether',
};
