trigger:
  - homolog

pool:
  vmImage: $(VM_IMAGE)

resources:
  repositories:
    - repository: centralized-templates
      type: git
      name: Infra/centralized-templates

variables:
  - group: azure-devops-iam-aws-dchomolog

stages:
  - stage: Deploy
    jobs:
      - job: DeployToS3Bucket
        steps:
          - template: yarn/install.yml@centralized-templates
          - template: yarn/build.yml@centralized-templates
          - template: s3/sync-files.yml@centralized-templates
